--CREA EL USUARIO Y CONTRASEÑA
CREATE USER POKEMON IDENTIFIED BY POKEMON ACCOUNT UNLOCK;

--DAR LOS PERMISOS AL USUARIO POKEMON
GRANT ALL PRIVILEGES TO POKEMON;

--SI DESEA BORRAR DESCOMENTAR LA SIGUIENTE SENTENCIA
--DROP USER POKEMON CASCADE;